// Code generated by Kitex v0.13.1. DO NOT EDIT.

package activityservice

import (
	activity_service "FlashSale/kitex_gen/FlashSale/activity_service"
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"CreateActivity": kitex.NewMethodInfo(
		createActivityHandler,
		newActivityServiceCreateActivityArgs,
		newActivityServiceCreateActivityResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	activityServiceServiceInfo                = NewServiceInfo()
	activityServiceServiceInfoForClient       = NewServiceInfoForClient()
	activityServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return activityServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return activityServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return activityServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "ActivityService"
	handlerType := (*activity_service.ActivityService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "activity_service",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.13.1",
		Extra:           extra,
	}
	return svcInfo
}

func createActivityHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*activity_service.ActivityServiceCreateActivityArgs)
	realResult := result.(*activity_service.ActivityServiceCreateActivityResult)
	success, err := handler.(activity_service.ActivityService).CreateActivity(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newActivityServiceCreateActivityArgs() interface{} {
	return activity_service.NewActivityServiceCreateActivityArgs()
}

func newActivityServiceCreateActivityResult() interface{} {
	return activity_service.NewActivityServiceCreateActivityResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) CreateActivity(ctx context.Context, req *activity_service.CreateActivityRequest) (r *activity_service.CreateActivityResponse, err error) {
	var _args activity_service.ActivityServiceCreateActivityArgs
	_args.Req = req
	var _result activity_service.ActivityServiceCreateActivityResult
	if err = p.c.Call(ctx, "CreateActivity", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
