// Code generated by Kitex v0.13.1. DO NOT EDIT.

package stockservice

import (
	stock_service "FlashSale/kitex_gen/FlashSale/stock_service"
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"DeductStock": kitex.NewMethodInfo(
		deductStockHandler,
		newStockServiceDeductStockArgs,
		newStockServiceDeductStockResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	stockServiceServiceInfo                = NewServiceInfo()
	stockServiceServiceInfoForClient       = NewServiceInfoForClient()
	stockServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return stockServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return stockServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return stockServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "StockService"
	handlerType := (*stock_service.StockService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "stock_service",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.13.1",
		Extra:           extra,
	}
	return svcInfo
}

func deductStockHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*stock_service.StockServiceDeductStockArgs)
	realResult := result.(*stock_service.StockServiceDeductStockResult)
	success, err := handler.(stock_service.StockService).DeductStock(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newStockServiceDeductStockArgs() interface{} {
	return stock_service.NewStockServiceDeductStockArgs()
}

func newStockServiceDeductStockResult() interface{} {
	return stock_service.NewStockServiceDeductStockResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) DeductStock(ctx context.Context, req *stock_service.DeductStockRequest) (r *stock_service.DeductStockResponse, err error) {
	var _args stock_service.StockServiceDeductStockArgs
	_args.Req = req
	var _result stock_service.StockServiceDeductStockResult
	if err = p.c.Call(ctx, "DeductStock", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
